### ISSUE TITLE
Some AJAX calls aren't using REACT_APP_DIRECTUS_ENDPOINT

### ISSUE THREAD

**Issue by gluxon** [SquaredLabs/Jeff-Website#16]
Clicking on `/working` and `/collaborating` while in local development seems to trigger this issue. Issue originally found by Chris.

**Comment by nhatphan108** [comment]
So apparently the links are hard links from the database and it links to localhost:3000/work instead of the jeffseemann site.  I think you might have to go into database and change it. It's the same case in the lab page and the about page.  It's at /api/1.1/tables/lab_content/rows and /api/1.1/tables/about/rows

**Comment by gluxon** [comment]
I just messaged you the login details to on Slack.
